---
- name: Destroy Infrastructure with Terraform
  terraform:
    project_path: "{{ playbook_dir }}/roles/tf-infrastructure/terraform"
    force_init: true
    state: absent
    variables:
      hcloud_token: "{{ hetzner_token }}"
      authorized_keys: "{{ ssh_authorized_keys | to_json }}"
      datacenter: "{{ datacenter }}"
      server_image: "{{ server_image }}"
      master_servertype: "{{ master_servertype }}"
      worker_servertype: "{{ worker_servertype }}"
      worker_count: "{{ worker_count }}"
      floatip_count: "{{ floatip_count }}"
  register: tf