---
- name: Reset previous configuration if exists
  shell: kubeadm reset -f

- name: Load Kubernetes Images
  shell: kubeadm config images pull

- name: Init Kubeadm - Kubernetes Master
  shell: |
    kubeadm init \
      --pod-network-cidr=10.244.0.0/16 \
      --kubernetes-version={{ kubenetes_version }} \
      --apiserver-cert-extra-sans=10.0.1.2 \
      --ignore-preflight-errors=NumCPU

- name: Create Kube-Config Folder
  file:
    path: /root/.kube
    state: directory

- name: Copy Kube-Config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

- name: Create Directory K8s yaml files
  file:
    path: /tmp/k8s-install
    state: directory

- name: Create a Hetzner Secret object
  shell: kubectl -n kube-system create secret generic hcloud --from-literal=network=kubernetes --from-literal=token="{{ hetzner_token }}"

- name: Copy yaml cloud-controller-manager for Hetzner Cloud Kubernetes Version
  get_url:
    url: https://raw.githubusercontent.com/hetznercloud/hcloud-cloud-controller-manager/master/deploy/v1.6.1-networks.yaml
    dest: /tmp/k8s-install/hcloud-controller.yaml

- name: Deploy Hetzner Cloud Controller Manager
  shell: kubectl apply -f /tmp/k8s-install/hcloud-controller.yaml

- name: Copy yaml Calico Network Plugin
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: /tmp/k8s-install/calico.yaml

- name: Deploy Calico Network Plugin
  shell: kubectl apply -f /tmp/k8s-install/calico.yaml

- name: Create a CSI Hetzner Secret object
  shell: kubectl -n kube-system create secret generic hcloud-csi --from-literal=network=kubernetes --from-literal=token="{{ hetzner_token }}"

- name: Get kube api manifests csidriver
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/csi-api/release-1.14/pkg/crd/manifests/csidriver.yaml
    dest: /tmp/k8s-install/csidriver.yaml

- name: Get kube api manifests csinodeinfo
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/csi-api/release-1.14/pkg/crd/manifests/csinodeinfo.yaml
    dest: /tmp/k8s-install/csinodeinfo.yaml

- name: Copy yaml HCloud CSI
  get_url:
    url: https://raw.githubusercontent.com/hetznercloud/csi-driver/master/deploy/kubernetes/hcloud-csi.yml
    dest: /tmp/k8s-install/hcloud-csi.yaml

- name: Deploy HCloud CSI hetznercloud/hcloud-csi-driver
  shell: |
    kubectl apply -f /tmp/k8s-install/csidriver.yaml \
    && kubectl apply -f /tmp/k8s-install/csinodeinfo.yaml \
    && kubectl apply -f /tmp/k8s-install/hcloud-csi.yaml

- name: Create Join Command for the nodes
  shell: kubeadm token create --print-join-command
  register: join

- name: Copy Kube-Config to Local Device
  slurp:
    src: /etc/kubernetes/admin.conf
  register: kubeconf

- name: Save Join to file
  local_action: copy content="{{ join.stdout }}" dest="/tmp/join.sh"
  vars:
     ansible_become: no

- name: Save kubeconf to local kubectl
  local_action: copy content="{{ kubeconf['content'] | b64decode }}" dest="{{ local_kube_context_path }}/config"
  vars:
     ansible_become: no