# Hetzner HCloud Project API Token
hetzner_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
# Public SSH Keys to connect instances with ssh
ssh_authorized_keys:
  - "{{ lookup('file', '~/.ssh/hetzner.pub') }}"
# Datacenter Name
datacenter: nbg1
# OS image
server_image: centos-7
# Master and Worker Server Types
master_servertype: cx11
worker_servertype: cx11
# Count Worker Nodes
worker_count: 1
# Count Pool IPs for Metal Load Balancer
floatip_count: 1
# Tested 1.15.5 and 1.16.2
kubenetes_version: 1.18.5
local_kube_context_path: ~/.kube
